/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness probe */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {string} */
              status: 'ok';
              /** @enum {string} */
              service: 'board-game-shop-api';
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/products': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List products (paginated) */
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              products: {
                id: number;
                name: string;
                description: string;
                tags: string[];
                authors: string;
                players: number[];
                playersDisplay: string;
                durationMin: number;
                ageMin: number;
                complexity: string;
                complexityLevel: number;
                year: number;
                rating: number;
                isExpansion: boolean;
                category: string;
                brand: string;
                image: string;
                priceCents: number;
              }[];
              page: number;
              pageSize: number;
              hasNext: boolean;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/products/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Product detail */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              id: number;
              name: string;
              description: string;
              tags: string[];
              authors: string;
              players: number[];
              playersDisplay: string;
              durationMin: number;
              ageMin: number;
              complexity: string;
              complexityLevel: number;
              year: number;
              rating: number;
              isExpansion: boolean;
              category: string;
              brand: string;
              image: string;
              priceCents: number;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error: string;
              message: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/carts/{customerId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** A customer's cart (empty for a never-seen customer) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          customerId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              customerId: string;
              items: {
                productId: number;
                name: string;
                image: string;
                unitPriceCents: number;
                quantity: number;
                lineTotalCents: number;
              }[];
              totalCents: number;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/carts/{customerId}/items/{productId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Set the quantity of a cart line (upsert) */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          customerId: string;
          productId: number;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            quantity: number;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              customerId: string;
              items: {
                productId: number;
                name: string;
                image: string;
                unitPriceCents: number;
                quantity: number;
                lineTotalCents: number;
              }[];
              totalCents: number;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error: string;
              message: string;
            };
          };
        };
      };
    };
    post?: never;
    /** Remove a cart line (idempotent) */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          customerId: string;
          productId: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              customerId: string;
              items: {
                productId: number;
                name: string;
                image: string;
                unitPriceCents: number;
                quantity: number;
                lineTotalCents: number;
              }[];
              totalCents: number;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/orders': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** A customer's order history, newest first */
    get: {
      parameters: {
        query: {
          customerId: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              orders: {
                id: number;
                customerId: string;
                createdAt: string;
                totalCents: number;
                items: {
                  productId: number;
                  name: string;
                  unitPriceCents: number;
                  quantity: number;
                  lineTotalCents: number;
                }[];
              }[];
            };
          };
        };
      };
    };
    put?: never;
    /** Checkout: build an order from the customer's cart and clear it */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            customerId: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              id: number;
              customerId: string;
              createdAt: string;
              totalCents: number;
              items: {
                productId: number;
                name: string;
                unitPriceCents: number;
                quantity: number;
                lineTotalCents: number;
              }[];
            };
          };
        };
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error: string;
              message: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/chat': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Conversational advisor turn with buyable recommendations */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            customerId: string;
            sessionId: string;
            message: string;
            /** @default [] */
            choices?: string[];
            /** @default 4 */
            k?: number;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              message: string;
              games: {
                id: number;
                name: string;
                image: string;
                priceCents: number;
                playersDisplay: string;
                durationMin: number;
                complexity: string;
              }[];
              quickReplies: string[];
            };
          };
        };
        /** @description Default Response */
        502: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error: string;
              message: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
